Toolbar buttons alignment
zowe/zlux-file-explorer pull request #178
Opened 2022-10-27 10:21 UTC by bobadesakshi21

Aligning the buttons in the toolbar after adding a new button to create the dataset
And renaming the tooltip to 'Allocate new dataset'

2022-11-09 15:22 UTC, DivergentEuropeans commented
Please next time @bobadesakshi21 for stuff like this, include screenshots to see the UI changes

2022-11-11 01:42 UTC, DivergentEuropeans requested changes
This is going to decrease the width of the search bar in places that don't hide it. We shouldn't add new buttons next to the refresh icon, we should add buttons in the icons toolbar

![image](https://user-images.githubusercontent.com/20528015/201243624-786b7c66-0c6f-405f-bff6-66dfc106a7e9.png)
from pink arrow to blue arrow

2022-11-11 01:43 UTC, DivergentEuropeans commented
It's an interesting spot but our UX will suffer if we keep adding buttons to multiple places. Let's use the toolbar for all the actions (outside the existing navigation actions, up the parent level and refresh)

2022-11-15 05:53 UTC, sakshibobade21 commented
> This is going to decrease the width of the search bar in places that don't hide it. We shouldn't add new buttons next to the refresh icon, we should add buttons in the icons toolbar
> 
> ![image](https://user-images.githubusercontent.com/20528015/201243624-786b7c66-0c6f-405f-bff6-66dfc106a7e9.png) from pink arrow to blue arrow

Makes sense. I will create a new ticket for the same

2022-12-15 12:59 UTC, sakshibobade21 commented
Closing this because now we have added the dataset creation button to the icons toolbar

2022-12-15 12:59 UTC, closed without merging